FROM debian:buster

RUN apt update -y && apt upgrade -y && apt-get install -y mariadb-server

COPY tools /var/www/

RUN chmod +x /var/www/data.sh

RUN sed -i 's/bind-address/#bind-adress/' /etc/mysql/mariadb.conf.d/50-server.cnf

EXPOSE 3360

ENTRYPOINT [ "/var/www/data.sh" ]

CMD ["mysqld"]



